[package]
name = "archives-node"
version = "0.1.5+tychov-e535d5c45b69b29711180a0f33f237194ccfe987"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
object_store = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tikv-jemalloc-ctl = { workspace = true }
tikv-jemallocator = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }

tycho-light-node = { workspace = true }
tycho-core = { workspace = true }
tycho-block-util = { workspace = true }
tycho-util = { workspace = true }

everscale-types = { workspace = true }

rayon = { workspace = true }

serde = { workspace = true }

futures-util = { workspace = true }

[lints]
workspace = true
